import{a as S,S as q,i as n}from"./assets/vendor-CIF6YjI2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="56198114-ccacac48ed3b4e5ff26b93aa4",B="https://pixabay.com/api/",d=15;async function m(r,t){return(await S.get(B,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:d}})).data}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more");let c=null;function y(r){const t=r.map(({webformatURL:s,largeImageURL:l,tags:e,likes:o,views:a,comments:v,downloads:E})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
          <div class="card-info">
            <p class="card-info-item"><b>Likes</b><span>${o}</span></p>
            <p class="card-info-item"><b>Views</b><span>${a}</span></p>
            <p class="card-info-item"><b>Comments</b><span>${v}</span></p>
            <p class="card-info-item"><b>Downloads</b><span>${E}</span></p>
          </div>
        </a>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),c?c.refresh():c=new q(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function R(){p.innerHTML="",c=null}function b(){g.classList.remove("hidden")}function C(){g.classList.add("hidden")}function L(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}const u=document.querySelector(".form"),$=document.querySelector(".load-more");let f="",i=1;u.addEventListener("submit",async r=>{r.preventDefault();const t=u.elements["search-text"].value.trim();if(t){f=t,i=1,R(),w(),b();try{const s=await m(f,i);if(s.hits.length===0){n.show({icon:"ico-error",iconColor:"#fff",title:"Error",titleColor:"#fff",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",timeout:5e3});return}y(s.hits),i*d<s.totalHits?L():n.show({icon:"ico-info",iconColor:"#fff",title:"Info",titleColor:"#fff",message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#4e75ff",position:"topRight",timeout:5e3})}catch(s){n.show({icon:"ico-error",iconColor:"#fff",title:"Error",titleColor:"#fff",message:s.message,messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",timeout:5e3})}finally{C()}}});$.addEventListener("click",async()=>{i+=1,b(),w();try{const r=await m(f,i);y(r.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),i*d>=r.totalHits?n.show({icon:"ico-info",iconColor:"#fff",title:"Info",titleColor:"#fff",message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#4e75ff",position:"topRight",timeout:5e3}):L()}catch(r){n.show({icon:"ico-error",iconColor:"#fff",title:"Error",titleColor:"#fff",message:r.message,messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",timeout:5e3})}finally{C()}});
//# sourceMappingURL=index.js.map
